### ISSUE TITLE
bpy.context has no user_preferences attribute [Blender 2.8]

### ISSUE THREAD

**Issue by KuboWu** [p2or/blender-viewport-rename#2]
Unfortunately, the addon does not work.

![image](https://user-images.githubusercontent.com/47286180/52170852-3286b000-2752-11e9-8bbe-54078a3eb248.png)

**Comment by p2or** [comment]
Thanks for reporting that issue @KuboWu. Obviously they changed how to access the user preferences in the last days. I think I fixed that by the latest commit and all is working again, otherwise just let me know.

Cheers,
Christian
