### ISSUE TITLE
Viewport_Rename - Dialog size

### ISSUE THREAD

**Issue by mond-cz** [p2or/blender-viewport-rename#4]
I'm not sure, but on my Retina display dialog box is too wide. https://imgur.com/mFJonuD
 It is set to `dialog_size = 450 * dpi * ui_size`

When I use value 100, it looks fine for me.

Thank you a lot for the reverse and sequential numbering :)
It's shame it is not a part  of official Batch Rename, so it can be find in one place.

**Comment by p2or** [comment]
Hi @mond-cz,

funny! Many thanks for your report and glad to hear that the add-on is still useful somehow. I just removed the multiplier (394feaa), tested the changes on a 13-inch MBP using Blender 2.82 and added a new release. If you have the time, please test it and report back whether the patch works: https://github.com/p2or/blender-viewport-rename/releases/latest Closing for now.

Cheers,
Christian

**Comment by mond-cz** [comment]
Thank you for your time :) Works great.

**Comment by p2or** [comment]
Hi @mond-cz, thanks for your feedback and your bug report! If you have any further ideas how to improve it, just let me know. Cheers!
